name: Publish
on:
  release:
    types: [published, edited]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu  # https://www.azul.com/downloads/?package=jdk
      - name: Build plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "build/distributions/idea-netcdf-plugin-*.zip"
