name: Test
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu  # https://www.azul.com/downloads/?package=jdk
      - name: Run all validation checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
