name: Test
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out project
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run all validation checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
